# Generated by Django 3.2.6 on 2021-10-07 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211005_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 9, 20, 58, 33, 414197, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
