# Generated by Django 3.2.8 on 2021-10-14 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211013_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 14, 25, 8, 878119, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
